version: '3.7'
services:
  backend:
    image: diogo8machado/ys
    ports:
      - 3333:3333
    environment:
      APP_URL: http://172.17.0.1:3333
      APP_SECRET: adwe@asd2234321@+
      NODE_ENV: production
      REDIS_HOST: 172.17.0.1
      REDIS_PORT: 6379
volumes:
  pg_data_ys:
